### ISSUE TITLE
Failed to load images in icons manifest entry.

### ISSUE THREAD

**Issue by muratyasarr** [george-botros/InspoTab#1]
![IMG_FF861FBB134B-1](https://user-images.githubusercontent.com/5808346/132348632-a10b3605-7f58-4a6a-876b-858e6a688ada.jpeg)
![image](https://user-images.githubusercontent.com/5808346/132348660-19db3247-6aa7-452d-8bbb-a79c4cbe6629.png)

**Comment by patrickshox** [comment]
It was still in development at that time. It's resolved now.
